---
name: Test-Run-CmdLine
version: 0.0107
author:
  - 'Shlomi Fish, C<< <shlomif@iglu.org.il> >>'
abstract: Analyze tests from the command line using Test::Run
license: mit
resources:
  license: http://opensource.org/licenses/mit-license.php
requires:
  Test::Run::Core: 0.0110
  UNIVERSAL::require: 0
build_requires:
  Test::More: 0
  Test::Trap: 0
provides:
  Test::Run::CmdLine:
    file: lib/Test/Run/CmdLine.pm
    version: 0.0107
  Test::Run::CmdLine::Drivers::Default:
    file: lib/Test/Run/CmdLine/Drivers/Default.pm
  Test::Run::CmdLine::Iface:
    file: lib/Test/Run/CmdLine/Iface.pm
  Test::Run::CmdLine::Prove:
    file: lib/Test/Run/CmdLine/Prove.pm
    version: 0.0100_05
  Test::Run::CmdLine::Prove::App:
    file: lib/Test/Run/CmdLine/Prove/App.pm
  Test::Run::CmdLine::Trap::Prove:
    file: lib/Test/Run/CmdLine/Trap/Prove.pm
  Test::Run::CmdLine::Trap::ProveApp:
    file: lib/Test/Run/CmdLine/Trap/ProveApp.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
