---
name: Test-Run-CmdLine
version: 0.0112
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
abstract: Analyze tests from the command line using Test::Run
license: mit
resources:
  homepage: http://web-cpan.berlios.de/modules/Test-Run/
  license: http://www.opensource.org/licenses/mit-license.php
  repository: http://svn.berlios.de/svnroot/repos/web-cpan/Test-Harness-NG/
build_requires:
  Test::More: 0
  Test::Trap: 0
requires:
  Test::Run::Core: 0.0118
  UNIVERSAL::require: 0
  YAML: 0
configure_requires:
  Module::Build: 0.3306
provides:
  Test::Run::CmdLine:
    file: lib/Test/Run/CmdLine.pm
    version: 0.0112
  Test::Run::CmdLine::Drivers::Default:
    file: lib/Test/Run/CmdLine/Drivers/Default.pm
  Test::Run::CmdLine::Iface:
    file: lib/Test/Run/CmdLine/Iface.pm
  Test::Run::CmdLine::Prove:
    file: lib/Test/Run/CmdLine/Prove.pm
    version: 0.0100_05
  Test::Run::CmdLine::Prove::App:
    file: lib/Test/Run/CmdLine/Prove/App.pm
  Test::Run::CmdLine::Trap::Prove:
    file: lib/Test/Run/CmdLine/Trap/Prove.pm
  Test::Run::CmdLine::Trap::ProveApp:
    file: lib/Test/Run/CmdLine/Trap/ProveApp.pm
generated_by: Module::Build version 0.3306
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
keywords:
  - cmdline
  - command-line
  - front-end
  - harness
  - prove
  - qa
  - QA
  - quality assurance
  - run
  - runprove
  - tap
  - TAP
  - TAP::Harness
  - test
  - testing
  - Test::Run
